import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [events, setEvents] = React.useState([
    { id: 110, name: "Football", price: 100, isSelected: false },
    { id: 120, name: "Basketball", price: 200, isSelected: false },
    { id: 130, name: "Tennis", price: 300, isSelected: false },
    { id: 140, name: "Volleyball", price: 400, isSelected: false },
  ]);
  const [total, setTotal] = React.useState(0);

  React.useEffect(() => {
    setTotal(
      events
        .filter((e) => e.isSelected)
        .reduce((acc, event) => acc + event.price, 0)
    );
  }, [events]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <h1 className={styles.title}>Welcome to Stripe payment Gateway!</h1>
        <div className={styles.bottom}>
          <aside>
            {events.map((event, index) => (
              <div
                className={`${styles.card} ${
                  event.isSelected ? styles.cardActive : ""
                }`}
                key={index}
              >
                <h2>
                  {event.name} <p>₹{event.price}</p>
                </h2>
                <button
                  className={`${event.isSelected ? styles.buttonActive : ""}`}
                  onClick={() =>
                    setEvents(
                      events.map((e) =>
                        e.id === event.id
                          ? { ...e, isSelected: !e.isSelected }
                          : e
                      )
                    )
                  }
                >
                  {event.isSelected ? "Remove" : "Add"}
                </button>
              </div>
            ))}
          </aside>
          <main className={styles.formContainer}>
            <div className={styles.cart}>
              <h2>Cart</h2>
              <ul>
                {events
                  .filter((e) => e.isSelected)
                  .map((event, index) => (
                    <li key={index}>
                      {event.name} - {event.price}
                    </li>
                  ))}
              </ul>
              <h2>
                Total:{" ₹"}
                {total}
              </h2>
            </div>
            <form
              onSubmit={(e) => {
                e.preventDefault();
                console.log(total);
              }}
            >
              <button type="submit">Checkout</button>
            </form>
          </main>
        </div>
      </div>
    </div>
  );
}
