import Head from "next/head";
import React from "react";
import styles from "../styles/RegisterEvent.module.css";
import initializeRazorpay from "../utils/initRazorpay";
import { useRouter } from "next/router";

export default function RegisterEvent() {
  const router = useRouter();
  const [user, setUser] = React.useState({ name: "" });
  const [events, setEvents] = React.useState([
    { id: 110, name: "Football", price: 100, isSelected: false },
    { id: 120, name: "Basketball", price: 200, isSelected: false },
    { id: 130, name: "Tennis", price: 300, isSelected: false },
    { id: 140, name: "Volleyball", price: 400, isSelected: false },
  ]);
  const [total, setTotal] = React.useState(0);

  React.useEffect(() => {
    const localUser = JSON.parse(localStorage.getItem("user"));
    localUser.userId ? router.push("/register-event") : router.push("/");
    setUser(localUser);
  }, []);

  React.useEffect(() => {
    setTotal(
      events
        .filter((e) => e.isSelected)
        .reduce((acc, event) => acc + event.price, 0)
    );
  }, [events]);

  async function makePayment() {
    const totalInPaise = total * 100;
    const res = await initializeRazorpay();
    if (!res) {
      console.log("Razorpay not initialized");
      return;
    }

    const data = await fetch("/api/razorpay", {
      method: "POST",
      body: JSON.stringify({
        amount: totalInPaise,
        notes: { line_items: JSON.stringify(events.filter((e) => e.isSelected)) },
      }),
    }).then((res) => res.json());

    const localData = JSON.parse(localStorage.getItem("Events"))
      ? JSON.parse(localStorage.getItem("Events"))
      : [];

    localStorage.setItem(
      "Events",
      JSON.stringify([
        ...localData,
        {
          total: total,
          Events: events,
          orderId: data.id,
          timeStamp: new Date().getTime(),
        },
      ])
    );

    const options = {
      key: process.env.RAZORPAY_KEY_ID,
      name: "Santhosh",
      currency: data.currency,
      amount: data.amount,
      order_id: data.id,
      description: "Payment for events",
      handler: function (response) {
        console.log(response);

        const newData = JSON.parse(localStorage.getItem("Events"));

        newData.forEach((event) => {
          if (event.orderId === data.id) {
            event.razorpay = response;
          }
        });

        localStorage.setItem("Events", JSON.stringify(newData));
        window.location.href = "/status";
      },
    };

    const payment = new window.Razorpay(options);
    payment.open();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <h1 className={styles.title}>Hi, {user.name}!</h1>
        <div className={styles.bottom}>
          <aside>
            {events.map((event, index) => (
              <div
                className={`${styles.card} ${
                  event.isSelected ? styles.cardActive : ""
                }`}
                key={index}
              >
                <h2>
                  {event.name} <p>₹{event.price} + {event.price * 0.02}</p>
                </h2>
                <button
                  className={`${event.isSelected ? styles.buttonActive : ""}`}
                  onClick={() =>
                    setEvents(
                      events.map((e) =>
                        e.id === event.id
                          ? { ...e, isSelected: !e.isSelected }
                          : e
                      )
                    )
                  }
                >
                  {event.isSelected ? "Remove" : "Add"}
                </button>
              </div>
            ))}
          </aside>
          <main className={styles.formContainer}>
            <div className={styles.cart}>
              <h2>Cart</h2>
              <ul>
                {events
                  .filter((e) => e.isSelected)
                  .map((event, index) => (
                    <li key={index}>
                      {event.name} - {event.price}
                    </li>
                  ))}
              </ul>
              <h2>
                Total:{" ₹"}
                {total}
              </h2>
            </div>
            <form
              onSubmit={async (e) => {
                e.preventDefault();
                await makePayment();
              }}
            >
              <button type="submit">Checkout</button>
            </form>
          </main>
        </div>
      </div>
    </div>
  );
}
